### ISSUE TITLE
MD word recording snippet incorporation

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#17] opened 2018-07-07 06:16 UTC
* standard reference in XML -> automated population based on validated snippets
* structured audio database extracted wholesale from validation source materials

**Comment by eddieantonio** [comment] 2018-10-02 21:15
Need to work on https://github.com/UAlbertaALTLab/recording-validation-interface first.

**Comment by eddieantonio** [comment] 2018-12-17 03:37
@aarppe is this a duplicate of #92?

**Comment by aarppe** [comment] 2018-12-17 03:40
Yes, or alternatively, #92 is a duplicate of this issue (as this was first).

**Comment by eddieantonio** [comment] 2018-12-17 03:44
Duplicate/predecessor of #92.

**Closed as completed by eddieantonio** 2018-12-17 03:44 UTC
Labels: duplicate, must have in second version
