### ISSUE TITLE
Discrepancy between (at least) SRO circumflex and SRO macron in search results

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#30] opened 2018-08-27 18:39 UTC
Results of search (analyses and presented normative forms) are not the same when using SRO circumflex vs. SRO macron. See search with 'nipihk' below:

![](https://user-images.githubusercontent.com/15003407/44677122-6666e800-a9f2-11e8-8be9-523993ec16a0.png)

![](https://user-images.githubusercontent.com/15003407/44677175-84344d00-a9f2-11e8-8a17-580bc03806bb.png)

Perplexingly, there the SRO circumflex descriptive analyzer provides one more analysis that the SRO macron analysis, cf.

echo nipihk | hfst-lookup -q src/analyser-gt-desc.hfstol | cut -f2
nipiy+N+I+Loc
nîpiy+N+I+Loc
nipiw+V+AI+Cnj+Prs+X
nîpin+V+II+Cnj+Prs+3Sg
nipiw+V+AI+Imp+Imm+2Pl

nipihk | hfst-lookup -q src/analyser-gt-desc.macron.hfstol | cut -f2
nipiy+N+I+Loc
nîpiy+N+I+Loc
nipiw+V+AI+Cnj+Prs+X
nîpin+V+II+Cnj+Prs+3Sg

But the difference between itwêwina output is more than one form (and even for SRO circumflex we only get 4 analyses forms). So there may be two issues here, an FST and an NDS one.

Besides fixing this, should we also have regression tests for this, i.e. the search results in all three orthographies?

**Comment by eddieantonio** [comment] 2018-08-29 15:46
Related to (but not a duplicate of) #31.

NDS seems to be doing the same thing it was doing with syllabics. I'll investigate further.

**Comment by eddieantonio** [comment] 2018-08-31 21:42
I got it working! All that remains now is #31.

**Comment by eddieantonio** [comment] 2018-09-04 16:30
The workaround that involves sharing the in-memory XML dictionary does not work, because the code _changes_ the mutable dictionary instances. That is, in order to look-up a word, the dictionary entries are themselves changed. This means that if a request uses a difference orthography, the results are changed permanently for both orthographies :/

**Comment by eddieantonio** [comment] 2018-09-12 23:48
This has been fixed as of 29fa79a0907e80e487f812a6ac2939fe7e03a4df.

**Closed as completed by eddieantonio** 2018-09-12 23:48 UTC
