### ISSUE TITLE
Weird orthography/language option menu of paradigm page

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/itwewina#74] opened 2018-09-21 05:22 UTC
We've ignored this until lately, but once on the paradigm generation page, the language/orthography options are not what they should, cf.

![image](https://user-images.githubusercontent.com/15003407/45861341-4d1f3600-bd29-11e8-903a-56bd05af11ca.png)

A. Functionality:
1. The first three options (1-3) do work in terms of search, but:
2. The last three options (4-6) don't make sense, referring to Cree-internal bilingual dictionaries (which we don't have), and thus result in an error message. What one should see here instead are the eng -> crk options (with the three data output orthograpies) - so the reverse of the first three. 

B. Presentation

The original idea was that the shorter buttons visible next to the search box on the paradigm page, and the longer versions visible when hovering/clicking on the button, would be the following:

SHORT              LONG
âêîô --> eng      nêhiyawêwin (âêîô) --> âkayâsîmowin
āēīō -> eng        nēhiyawēwin (āēīō) --> ākayāsīmowin
ᐋᐁᐄᐆ --> eng   nêhiyawêwin (ᐋᐁᐄᐆ) --> akayâsimowin
eng --> âêîô.      âkayâsîmowin --> nêhiyawêwin (âêîô) 
eng --> āēīō       ākayāsīmowin  --> nēhiyawēwin (āēīō)
eng --> ᐋᐁᐄᐆ    akayâsimowin --> nêhiyawêwin (ᐋᐁᐄᐆ) 

This is not a deal-breaker to keep us from releasing soon, but we're sure to get some feedback on this feature.

**Comment by eddieantonio** [comment] 2018-09-21 15:49
Duplicate of #9.

**Closed as completed by eddieantonio** 2018-09-21 15:49 UTC
Labels: duplicate, Nuisance
